In [1]:
import numpy as np

In [4]:
def calculate(input):
    if len(input) !=9:
        raise ValueError("List must contain nine numbers")
    print (input)
    
    a=np.array(input).reshape(3,3)
    print(a)
    print(a.mean(0).tolist(), a.mean(1).tolist(), a.mean())
    
    cal = dict()
    cal['mean'] = [a.mean(0).tolist(), a.mean(1).tolist(), a.mean()]
    cal['variance'] = [a.var(0).tolist(), a.var(1).tolist(), a.var()]
    cal['standar deviation'] = [a.std(0).tolist(), a.std(1).tolist(), a.std()]
    cal['max'] = [a.max(0).tolist(), a.max(1).tolist(), a.max()]
    cal['min'] = [a.min(0).tolist(), a.min(1).tolist(), a.min()]
    cal['sum'] = [a.sum(0).tolist(), a.sum(1).tolist(), a.sum()]
    return cal

    
print(calculate([0,1,2,3,4,5,6,7,8,]))

[0, 1, 2, 3, 4, 5, 6, 7, 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[3.0, 4.0, 5.0] [1.0, 4.0, 7.0] 4.0
{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0], 'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667], 'standar deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611], 'max': [[6, 7, 8], [2, 5, 8], 8], 'min': [[0, 1, 2], [0, 3, 6], 0], 'sum': [[9, 12, 15], [3, 12, 21], 36]}
